### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by jabuschh** [UHH2/ZprimeSemiLeptonic#188]
Things to be implemented/checked/added for the different stages of the analysis, i.e. before rerunning!

# 1. Preselection
- [x] fix the jet pt cut (20/30 GeV for >3rd-leading jets?) -> done #192 
- [x] update all needed (preselection) config xmls to the latest version (after the 2nd dCache issues)-> done UL17 in #193, done UL16preVFP in #210, done UL16postVFP in #212 
- [x] save histograms for normalizing systematic uncertainties -> `sum_event_weights(_PDF)` histograms which are filled at the very beginning of the preselection should be enough: store also for `mcscale` and `isr+fsr` -> done in #190 -> added fix for mscale and Diboson + RSGluon samples #195
- [x] setup xml configs for JEC and JER variations -> done (direct push)
- [x] add PV filter (it is disabled in the CommonModules) -> done #191 
- [x] update config UL18 -> done #232, #233

## Current Status
all files (nominal, JEC up/down, JER up/down) available for all years

# 2. Baseline Selection
- [x] save all histograms for all systematic variations -> done in #189 
- [x] For JEC and JER variations -> comment out our custom JEC/JER implementation, not needed -> done in #197 
- [x] update b-tagging SFs: they are available now: https://github.com/UHH2/UHH2/pull/1661) -> config xmls updated in #204
- [x] update top tagging WPs using the ones Christopher derived -> #208
- [x] implement top-tagging SFs (will be provided by Christopher in February) -> #230 
- [x] change MET and jet2 pT cuts -> #231
- [x] for UL18 ele: check HEM veto for MC -> #235
- [X] update config UL16preVFP-> #245 & #246 
- [x] update config UL16postVFP -> #245
- [x] update config UL18 -> #269 
- [x] check application of jet veto maps -> minor 2-3% effect on both DATA and MC which does not improve DATA/MC agreement -> not needed to be applied

### UL16preVFP
- [x] nominal
- [x] JEC
- [x] JER
### UL16postVFP
- [x] nominal
- [x] JEC
- [x] JER
### UL17
- [x] nominal
- [x] JEC
- [x] JER
### UL18
- [x] nominal
- [x] JEC
- [x] JER

# 3. DNN Application
- [x] change binning Mtt histograms (finer binning + extend x-axis range) -> done in #225 
- [x] add b-tagging syst in quadrature -> is treated like this in plotting script by default + can be done later for combine
- [x] update config UL16preVFP -> #277
- [x] update config UL16postVFP -> #276 
- [x] update config UL18 -> #272 
- [x] implement top-mistag measurement in W+Jets CR -> #280 
- [x] do top-mistag measurement
   - [ ] implement derived SFs
- [x] check if cuts on DNN output scores improve sensitivity -> work in progress (Henrik)
- [x] remove ``ìs_mc``` from [here](https://github.com/UHH2/ZprimeSemiLeptonic/blob/RunII_106X_v2/src/ZprimeSemiLeptonicHists.cxx#L1315) to be able to run background only fits in CRs ->#284

### UL16preVFP
- [x] nominal 
- [x] JEC
- [x] JER
### UL16postVFP
- [x] nominal
- [x] JEC
- [x] JER
### UL17
- [x] nominal
- [x] JEC
- [x] JER
### UL18
- [x] nominal
- [x] JEC
- [x] JER

# General: Analysis Note/Object Review/etc
- [ ] add statistical tests
- [ ] add Z' DM samples and propagate through analysis chain
       - UL16preVFP -> running presel 
- [ ] rerun UL18 data (after lumi sections were updated) 
- [ ] rerun diboson samples with (N)NLO k-factors
       - UL16preVFP -> running presel 
- [x] add top mistag rate SFs including uncertainties -> #285
